---
default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["pre-commit", "pre-push"]
exclude: ^(dist/.*\.js|coverage/.*|\.yarn/.*)$
minimum_pre_commit_version: 2.18.0
repos:
  # Linting
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: prettier --write --ignore-unknown
        language: node
        types: [text]
        args: []
        files: ^(.*\.md|.*\.yaml|.*\.yml)$
        # https://github.com/prettier/prettier/releases
        additional_dependencies: ["prettier@3.4.2"]
        stages: ["pre-commit"]
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/fabasoad/pre-commit-grype
    rev: v0.6.3
    hooks:
      - id: grype-dir
        args:
          - --grype-args=--by-cve --fail-on=low
          - --hook-args=--log-level debug
        stages: ["pre-push"]
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-fix
        stages: ["pre-commit"]
  # Shell
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        args: ["-i", "E003,E006"]
        stages: ["pre-commit"]
  # Yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.36.2
    hooks:
      - id: yamllint
        stages: ["pre-push"]
  # GitHub Actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        args: ["-pyflakes="]
        stages: ["pre-commit"]
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
        stages: ["pre-commit"]
      - id: check-shebang-scripts-are-executable
        stages: ["pre-commit"]
      - id: check-merge-conflict
      - id: check-json
        stages: ["pre-push"]
      - id: check-toml
        stages: ["pre-push"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        stages: ["pre-commit"]
      - id: trailing-whitespace
