---
name: NSFW Detection Action
author: Yevhen Fabizhevskyi
description: This GitHub Action detects NSFW content in committed files.
branding:
  icon: alert-octagon
  color: red
inputs:
  provider:
    description: Provider identifier.
    required: true
  api-key:
    description: API key required for the selected provider.
    required: true
  threshold:
    description: |
      The action will fail if the NSFW detection value is greater than or equal
      to this parameter.
    required: true
  extensions:
    description: Comma-separated list of file extensions for NSFW detection.
    required: false
    default: jpeg,jpg,png,gif,webp,tiff,bmp
  types:
    description: Comma-separated types of changes made during work on the branch.
    required: false
    default: added,copied,modified,renamed
runs:
  using: composite
  steps:
    - name: Validate inputs
      if: env.SCAN_SCA_EXIT_CODE == '0'
      id: validate-inputs
      env:
        INPUT_PROVIDER: "${{ inputs.provider }}"
        INPUT_API_KEY: "${{ inputs.api-key }}"
        INPUT_THRESHOLD: "${{ inputs.threshold }}"
        INPUT_EXTENSIONS: "${{ inputs.extensions }}"
        INPUT_TYPES: "${{ inputs.types }}"
      run: |
        ./validate-inputs.sh \
          "${INPUT_PROVIDER}" \
          "${INPUT_API_KEY}" \
          "${INPUT_THRESHOLD}" \
          "${INPUT_EXTENSIONS}" \
          "${INPUT_TYPES}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: "**.{${{ inputs.extensions }}}"

    - name: Setup jq
      if: (
        steps.changed-files.outputs.added_files_count != '0'
        || steps.changed-files.outputs.copied_files_count != '0'
        || steps.changed-files.outputs.modified_files_count != '0'
        || steps.changed-files.outputs.renamed_files_count != '0'
        )
      uses: dcarbone/install-jq-action@v3

    - name: Classify added files
      if: (
        contains(format(',{0},', inputs.types), ',added,')
        && steps.changed-files.outputs.added_files_count != '0'
        )
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
      run: |
        ${GITHUB_ACTION_PATH}/src/providers/${INPUT_PROVIDER}.sh \
          "${{ steps.changed-files.outputs.added_files }}" \
          "created" \
          "${INPUT_API_KEY}" \
          "${INPUT_THRESHOLD}"
      shell: sh

    - name: Classify copied files
      if: (
        contains(format(',{0},', inputs.types), ',copied,')
        && steps.changed-files.outputs.copied_files_count != '0'
        )
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
      run: |
        ${GITHUB_ACTION_PATH}/src/providers/${INPUT_PROVIDER}.sh \
          "${{ steps.changed-files.outputs.copied_files }}" \
          "copied" \
          "${INPUT_API_KEY}" \
          "${INPUT_THRESHOLD}"
      shell: sh

    - name: Classify modified files
      if: (
        contains(format(',{0},', inputs.types), ',modified,')
        && steps.changed-files.outputs.modified_files_count != '0'
        )
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
      run: |
        ${GITHUB_ACTION_PATH}/src/providers/${INPUT_PROVIDER}.sh \
          "${{ steps.changed-files.outputs.modified_files }}" \
          "modified" \
          "${INPUT_API_KEY}" \
          "${INPUT_THRESHOLD}"
      shell: sh

    - name: Classify renamed files
      if: (
        contains(format(',{0},', inputs.types), ',renamed,')
        && steps.changed-files.outputs.renamed_files_count != '0'
        )
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
      run: |
        ${GITHUB_ACTION_PATH}/src/providers/${INPUT_PROVIDER}.sh \
          "${{ steps.changed-files.outputs.renamed_files }}" \
          "renamed" \
          "${INPUT_API_KEY}" \
          "${INPUT_THRESHOLD}"
      shell: sh

    - name: Print message
      if: (
        (
        !contains(format(',{0},', inputs.types), ',added,')
        || steps.changed-files.outputs.added_files_count == '0'
        )
        && (
        !contains(format(',{0},', inputs.types), ',copied,')
        || steps.changed-files.outputs.copied_files_count == '0'
        )
        && (
        !contains(format(',{0},', inputs.types), ',modified,')
        || steps.changed-files.outputs.modified_files_count == '0'
        )
        && (
        !contains(format(',{0},', inputs.types), ',renamed,')
        || steps.changed-files.outputs.renamed_files_count == '0'
        )
        )
      run: |
        . ./logging.sh
        log_info "No files found for classification"
      shell: sh
      working-directory: ${{ github.action_path }}/src/lib
