---
name: NSFW Detection Action
author: Yevhen Fabizhevskyi
description: This GitHub Action detects NSFW content in committed files.
branding:
  icon: alert-octagon
  color: red
inputs:
  provider:
    description: Provider identifier.
    required: true
  api-key:
    description: API key required for the selected provider.
    required: true
  threshold:
    description: |
      The action will fail if the NSFW detection value is greater than or equal
      to this parameter.
    required: true
  extensions:
    description: Comma-separated list of file extensions for NSFW detection.
    required: false
    default: jpeg,jpg,png,gif,webp,tiff,bmp
  types:
    description: Comma-separated types of changes made during work on the branch.
    required: false
    default: added,copied,modified,renamed
runs:
  using: composite
  steps:
    - name: Validate inputs
      if: env.SCAN_SCA_EXIT_CODE == '0'
      id: validate-inputs
      env:
        INPUT_PROVIDER: "${{ inputs.provider }}"
        INPUT_API_KEY: "${{ inputs.api-key }}"
        INPUT_THRESHOLD: "${{ inputs.threshold }}"
        INPUT_EXTENSIONS: "${{ inputs.extensions }}"
        INPUT_TYPES: "${{ inputs.types }}"
      run: |
        ./validate-inputs.sh \
          "${INPUT_PROVIDER}" \
          "${INPUT_API_KEY}" \
          "${INPUT_THRESHOLD}" \
          "${INPUT_EXTENSIONS}" \
          "${INPUT_TYPES}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: "**.{${{ inputs.extensions }}}"

    #    - name: Get changed files
    #      id: get-changed-files
    #      env:
    #        INPUT_TYPES: "${{ inputs.types }}"
    #        INPUT_EXTENSIONS: "${{ inputs.extensions }}"
    #      run: |
    #        ${GITHUB_ACTION_PATH}/src/get-changed-files.sh \
    #          "${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}" \
    #          "${{ github.event.pull_request.head.sha }}" \
    #          "${INPUT_TYPES}" \
    #          "${INPUT_EXTENSIONS}"
    #      shell: sh

    - name: Setup jq
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      uses: dcarbone/install-jq-action@v3

    - name: Classify files
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
      run: ./${INPUT_PROVIDER}.sh "${{ steps.changed-files.outputs.all_changed_files }}"
      shell: sh
      working-directory: "${{ github.action_path }}/src/providers"
